version: '3'

services: 
  web:
    build: .
    command: gunicorn delivery_app.wsgi --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports: 
      - 80:80
    depends_on:
      - web
