# Generated by Django 3.0.2 on 2020-07-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='email',
            field=models.EmailField(default='dasdasd@asdasd.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
