# Generated by Django 3.0.2 on 2020-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
