# Generated by Django 3.0.2 on 2020-07-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0002_auto_20200703_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
