# Generated by Django 3.0.2 on 2020-06-18 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_logic', '0002_node_oauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='owner',
        ),
        migrations.AddField(
            model_name='node',
            name='owners',
            field=models.ManyToManyField(related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='workers',
            field=models.ManyToManyField(related_name='workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
