# Generated by Django 3.0.2 on 2020-03-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0002_auto_20200213_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
