# Generated by Django 3.0.2 on 2020-06-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0003_auto_20200618_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
