# Generated by Django 3.0.2 on 2020-06-19 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_logic', '0004_node_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='of_node_partner',
            new_name='of_node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='owners',
        ),
        migrations.AddField(
            model_name='node',
            name='co_owners',
            field=models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='owner',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
