# Generated by Django 3.0.2 on 2020-07-16 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0005_order_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
