# Generated by Django 3.0.2 on 2020-08-19 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0008_order_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='result',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
