# Generated by Django 3.0.2 on 2020-08-19 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0009_auto_20200819_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='error_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
