# Generated by Django 3.0.2 on 2020-06-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0005_auto_20200619_2223'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='of_node',
            field=models.ManyToManyField(to='business_logic.Node'),
        ),
    ]
