# Generated by Django 3.0.2 on 2020-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('business_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='of_node',
            field=models.ManyToManyField(to='business_logic.Node'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
